apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-map-brasil
  namespace: semana-devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-map-brasil
  minReplicas: 3
  maxReplicas: 9
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
